server {
    listen 80;
    server_name localhost;

    root /var/www/html/cardgame_project/MatchTheCard_GameMainScreen;
    index MainScreen.html;

    location / {
        try_files $uri $uri/ /MainScreen.html;

        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'Origin, Content-Type, Accept, Authorization' always;

        if($request_method = OPTIONS) {
                return 204;
        }
    }

    location ~ \.php$ {
        root /var/www/html;
        include fastcgi_params;
        fastcgi_pass php-backend:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_script_name;

        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTION' always;
        add_header 'Access-Control-Allow-Headers' 'Origin, Content-Type, Accept, Authorization' always;
    }
}
