version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-backend
    restart: always
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: card-nginx
    restart: always
    ports:
      - "13131:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mariadb:10.5
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootcard
      MYSQL_DATABASE: cardgame
      MYSQL_USER: carduser
      MYSQL_PASSWORD: mycard
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
